### ISSUE TITLE
auto_contrast and search_convert both generate an additional empty sub-directory

### ISSUE THREAD

**Issue by LaneYahtzee** [pvalle6/ImageJ_Automated_Macro#12]
Both scripts generate an additional empty sub-directory under the name of the directory. They then throw an error about missing files. Error message below for both.

(venv) b0-be-83-4c-13-58:Lane_Request_TIF2JPEG junglab$ python search_convert.py 
[ERROR] Cannot create plugin: org.scijava.plugins.scripting.javascript.JavaScriptScriptLanguage
Operating in headless mode - the original ImageJ will have limited functionality.
[INFO] null = <html><body><p>Bud1
(20x 210k (20x 250ms)lg1Scomp�R<code>10k (20x 250ms)moDDblo;������A10k (20x 250ms)modDblo;������A10k (20x 250ms)ph1Scomp��25k (20x 250ms)lg1Scomp�R</code>25k (20x 250ms)moDDblo�.�����A25k (20x 250ms)modDblo�.�����A25k (20x 250ms)ph1Scomp��50k (20x 250ms)lg1Scomp�8�50k (20x 250ms)moDDblob
                                               ������A50k (20x 250ms)modDblob
                                                                            ������A50k (20x 250ms)ph1Scomp��5k (20x 250ms)lg1Scomp�Rl5k (20x 250ms)moDDblo�G����A5k (20x 250ms)modDblo�G����A5k (20x 250ms)ph1Scomp��
                                                     @� @ @ @
                                                             E
DSDB ` @ @ @</p>
</body></html>
[java.lang.Enum.toString] [INFO] null = <html><body><p>Bud1
(20x 210k (20x 250ms)lg1Scomp�R<code>10k (20x 250ms)moDDblo;������A10k (20x 250ms)modDblo;������A10k (20x 250ms)ph1Scomp��25k (20x 250ms)lg1Scomp�R</code>25k (20x 250ms)moDDblo�.�����A25k (20x 250ms)modDblo�.�����A25k (20x 250ms)ph1Scomp��50k (20x 250ms)lg1Scomp�8�50k (20x 250ms)moDDblob
                                               ������A50k (20x 250ms)modDblob
                                                                            ������A50k (20x 250ms)ph1Scomp��5k (20x 250ms)lg1Scomp�Rl5k (20x 250ms)moDDblo�G����A5k (20x 250ms)modDblo�G����A5k (20x 250ms)ph1Scomp��
                                                     @� @ @ @
                                                             E
DSDB ` @ @ @</p>
</body></html>
There are no images open
[java.lang.Enum.toString] There are no images open[java.lang.Enum.toString] 

(venv) b0-be-83-4c-13-58:Lane_Request_TIF2JPEG junglab$ python autocontrast.py 
[ERROR] Cannot create plugin: org.scijava.plugins.scripting.javascript.JavaScriptScriptLanguage
Operating in headless mode - the original ImageJ will have limited functionality.
[INFO] null = <html><body><p>Bud1
(20x 210k (20x 250ms)dsclbool10k (20x 250ms)lg1Scomp
                                                    ��10k (20x 250ms)moDDbloWo76���A10k (20x 250ms)modDbloWo76���A10k (20x 250ms)ph1Scomp
                                                         25k (20x 250ms)dsclbool25k (20x 250ms)lg1Scomp
                       �25k (20x 250ms)moDDblo�E�6���A25k (20x 250ms)modDblo�E�6���A25k (20x 250ms)ph1Scomp
                           `50k (20x 250ms)dsclbool50k (20x 250ms)lg1Scomp�.50k (20x 250ms)moDDbloiV�5���A50k (20x 250ms)modDbloiV�5���A50k (20x 250ms)ph1Scomp5k (20x 250ms)dsclbool5k (20x 250ms)lg1Scomp<em>�J5k (20x 250ms)moDDbloN�U5���A5k (20x 250ms)modDbloN�U5���A5k (20x 250ms)ph1Scomp</em>�
                                                       @� @ @ @
                                                               E
DSDB ` @ @ @</p>
</body></html>
[java.lang.Enum.toString] [INFO] null = <html><body><p>Bud1
(20x 210k (20x 250ms)dsclbool10k (20x 250ms)lg1Scomp
                                                    ��10k (20x 250ms)moDDbloWo76���A10k (20x 250ms)modDbloWo76���A10k (20x 250ms)ph1Scomp
                                                         25k (20x 250ms)dsclbool25k (20x 250ms)lg1Scomp
                       �25k (20x 250ms)moDDblo�E�6���A25k (20x 250ms)modDblo�E�6���A25k (20x 250ms)ph1Scomp
                           `50k (20x 250ms)dsclbool50k (20x 250ms)lg1Scomp�.50k (20x 250ms)moDDbloiV�5���A50k (20x 250ms)modDbloiV�5���A50k (20x 250ms)ph1Scomp5k (20x 250ms)dsclbool5k (20x 250ms)lg1Scomp<em>�J5k (20x 250ms)moDDbloN�U5���A5k (20x 250ms)modDbloN�U5���A5k (20x 250ms)ph1Scomp</em>�
                                                       @� @ @ @
                                                               E
DSDB ` @ @ @</p>
</body></html>
Macro Error: There are no images open in line 5
 
run ( "Enhance Contrast" , "saturated=0.35" <)> ; [java.lang.Enum.toString] Macro Error: There are no images open in line 5
 
run ( "Enhance Contrast" , "saturated=0.35" <)> ; 
[java.lang.Enum.toString] 
(venv) b0-be-83-4c-13-58:Lane_Request_TIF2JPEG junglab$

**Comment by pvalle6** [comment]
Thank you Lane, I will get right on this!
